version: 0.0
os: linux
files:
  - source: /index.php
    destination: /var/www/html/
permissions:
  - object: /var/www/
    owner: root
    group: root
    mode: 777    
hooks:
  BeforeInstall:
    - location: before_start.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: after_start.sh
      timeout: 300
      runas: root
