version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: /var/www/html/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /var/www/html/restart_server.sh
      timeout: 300
      runas: root
