version: 0.2

phases:
  pre_build:
    commands:
      - curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer && chmod +x /usr/local/bin/composer
      - composer install
